-- ====================================
-- DOCUMENTATION: Team naming in matches
-- ====================================
--
-- SQLite (local storage):
-- - Uses my_team_name and opponent_name for clarity
-- - my_team_name: The name of the user's team
-- - opponent_name: The name of the opponent team
--
-- Supabase (cloud storage):
-- - Uses team_a_name and team_b_name for neutrality
-- - team_a_name: Usually corresponds to my_team_name (the home team or user's team)
-- - team_b_name: Usually corresponds to opponent_name (the away team)
--
-- When syncing from SQLite to Supabase:
-- - my_team_name → team_a_name
-- - opponent_name → team_b_name
--
-- When syncing from Supabase to SQLite:
-- - team_a_name → my_team_name (if the match was created by the current user)
-- - team_b_name → opponent_name
--
-- Note: This migration file is for documentation purposes only.
-- The Supabase schema already has team_a_name and team_b_name.
-- No changes are needed to the Supabase schema.
